inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    # n_dims: 5
    n_dims: 1
    n_positions: 11

training:
    # task: linear_regression
    task: sin_regression
    # data: gaussian
    data: uniform
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 10000
    train_steps: 50001
    curriculum:
        dims:
            # start: 5
            # end: 5
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 11
            inc: 2
            interval: 2000

out_dir: ../models/sin_regression

wandb:
    name: "sin_regression_toy"
